### PR TITLE
1903 codesmells

### PR DESCRIPTION
**Pull request by andrewtmcb**
Please review this code and pull

### CODE REVIEW

**Review by Mattxjt — DISMISSED** [review]
Make sure you also remove unwanted comments. Remove the comments related to the code you just remove.

**Review by Quinn-Donnelly — DISMISSED** [review]
Please ignore .scannerwork from the repo.

**Review by andrewtmcb — COMMENTED** [review]
Including .gitignore for .scanner work

**Comment by andrewtmcb** [comment]
writing new pull request.. some code changes abandoned

**Pull request closed without merging**
